// Base types for parameters
export interface BaseWeatherParams {
  lat: number;
  lon: number;
  units?: 'standard' | 'metric' | 'imperial';
}

export interface CurrentWeatherParams extends BaseWeatherParams {}

export interface ForecastParams extends BaseWeatherParams {}

export interface OneCallParams extends BaseWeatherParams {
  exclude?: string; // Comma-separated list of data blocks to exclude: current,minutely,hourly,daily,alerts
}

export interface AirPollutionParams {
  lat: number;
  lon: number;
}

// Geocoding parameters
export interface GeocodingParams {
  query: string;
  limit?: number;
}

export interface ReverseGeocodingParams {
  lat: number;
  lon: number;
  limit?: number;
}

// Daily Forecast parameters
export interface DailyForecastParams extends BaseWeatherParams {
  cnt?: number; // Number of days (1-16)
}

// Historical Weather parameters
export interface HistoricalWeatherParams extends BaseWeatherParams {
  dt: number; // Timestamp for historical data
}

// Solar API parameters
export interface SolarParams extends BaseWeatherParams {
  date?: string; // Date in YYYY-MM-DD format
  capacity?: number; // Solar panel capacity in kW
  angle?: number; // Panel angle
  aspect?: number; // Panel azimuth
}

// Union type for all weather card parameters
export type WeatherParams = 
  | CurrentWeatherParams 
  | ForecastParams 
  | OneCallParams 
  | AirPollutionParams
  | GeocodingParams
  | ReverseGeocodingParams
  | DailyForecastParams
  | HistoricalWeatherParams
  | SolarParams;

// Card type definition
export interface WeatherCardType {
  type: 'current' | 'forecast' | 'onecall' | 'air_pollution' | 'geocoding' | 'reverse_geocoding' | 'daily_forecast' | 'historical' | 'solar';
  parameters: WeatherParams;
  rationale?: string; // Only provided when generated by Gemini
}

// Layout definition
export interface WeatherLayout {
  cards: WeatherCardType[];
}

// Weather data response types
export interface CurrentWeatherData {
  weather: Array<{
    id: number;
    main: string;
    description: string;
    icon: string;
  }>;
  main: {
    temp: number;
    feels_like: number;
    temp_min: number;
    temp_max: number;
    pressure: number;
    humidity: number;
  };
  wind: {
    speed: number;
    deg: number;
    gust?: number;
  };
  clouds: {
    all: number;
  };
  visibility: number;
  dt: number;
  sys: {
    country: string;
    sunrise: number;
    sunset: number;
  };
  timezone: number;
  name: string;
}

export interface ForecastData {
  list: Array<{
    dt: number;
    main: {
      temp: number;
      feels_like: number;
      temp_min: number;
      temp_max: number;
      pressure: number;
      humidity: number;
    };
    weather: Array<{
      id: number;
      main: string;
      description: string;
      icon: string;
    }>;
    clouds: {
      all: number;
    };
    wind: {
      speed: number;
      deg: number;
      gust?: number;
    };
    visibility: number;
    pop: number; // Probability of precipitation
    dt_txt: string;
  }>;
  city: {
    name: string;
    country: string;
    sunrise: number;
    sunset: number;
  };
}

export interface AirPollutionData {
  list: Array<{
    dt: number;
    main: {
      aqi: number; // Air Quality Index
    };
    components: {
      co: number; // Carbon monoxide
      no: number; // Nitrogen monoxide
      no2: number; // Nitrogen dioxide
      o3: number; // Ozone
      so2: number; // Sulphur dioxide
      pm2_5: number; // Fine particles
      pm10: number; // Coarse particulate matter
      nh3: number; // Ammonia
    };
  }>;
}

export interface GeocodingData extends Array<{
  name: string;
  local_names?: Record<string, string>;
  lat: number;
  lon: number;
  country: string;
  state?: string;
}> {}

export interface DailyForecastData {
  list: Array<{
    dt: number;
    sunrise: number;
    sunset: number;
    temp: {
      day: number;
      min: number;
      max: number;
      night: number;
      eve: number;
      morn: number;
    };
    feels_like: {
      day: number;
      night: number;
      eve: number;
      morn: number;
    };
    pressure: number;
    humidity: number;
    weather: Array<{
      id: number;
      main: string;
      description: string;
      icon: string;
    }>;
    speed: number;
    deg: number;
    clouds: number;
    pop: number;
    rain?: number;
  }>;
  city: {
    name: string;
    country: string;
    coord: {
      lat: number;
      lon: number;
    };
    timezone: number;
  };
}

export interface HistoricalWeatherData {
  data: Array<{
    dt: number;
    temp: number;
    feels_like: number;
    pressure: number;
    humidity: number;
    weather: Array<{
      id: number;
      main: string;
      description: string;
      icon: string;
    }>;
    wind_speed: number;
    wind_deg: number;
    clouds: number;
    precipitation?: number;
  }>;
  city_name: string;
  lat: number;
  lon: number;
  timezone: number;
}

export interface SolarData {
  current: {
    ghi: number; // Global Horizontal Irradiance (W/m²)
    dni: number; // Direct Normal Irradiance (W/m²)
    dhi: number; // Diffuse Horizontal Irradiance (W/m²)
    ghi_clear: number; // Clear-sky Global Horizontal Irradiance (W/m²)
    dni_clear: number; // Clear-sky Direct Normal Irradiance (W/m²)
    dhi_clear: number; // Clear-sky Diffuse Horizontal Irradiance (W/m²)
    cloud_coverage: number; // Cloud coverage (%)
    generation?: number; // Photovoltaic power generation (kW)
  };
  forecast?: Array<{
    date: string;
    ghi: number;
    dni: number;
    dhi: number;
    cloud_coverage: number;
    generation?: number;
  }>;
} 